//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Nom est obligatoire", AllowEmptyStrings = false)]
        public string nom { get; set; }
        [Required(ErrorMessage = "Prenom est obligatoire", AllowEmptyStrings = false)]
        public string prenom { get; set; }
        [Required]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Email incorrect")]
        public string email { get; set; }
        [Required]
        public string codesecret { get; set; }
    }
}
