//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.message = new HashSet<message>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Nom est obligatoire", AllowEmptyStrings = false)]
        public string nom { get; set; }
        [Required(ErrorMessage = "Prénom est obligatoire", AllowEmptyStrings = false)]
        public string prenom { get; set; }
        [Required(ErrorMessage = "Age doit être entre 14 et 100", AllowEmptyStrings = false)]
        [Range(14, 100)]
        public int age { get; set; }
        [Required]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Email incorrect")]
        public string email { get; set; }
        [Required]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Téléphone incorrect")]
        public string telephone { get; set; }
        [Required(ErrorMessage = "Sélectionner une option", AllowEmptyStrings = false)]
        public string sexe { get; set; }
        [Required]
        public string adresse { get; set; }
        [Required]
        [StringLength(maximumLength: 9, MinimumLength = 9)]
        public string cin { get; set; }
        [StringLength(maximumLength: 100, MinimumLength = 6)]
        public string password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> message { get; set; }
    }
}
