//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspprojet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerceEntities1 : DbContext
    {
        public ecommerceEntities1()
            : base("name=ecommerceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<messageprop> messageprop { get; set; }
        public virtual DbSet<offre> offre { get; set; }
        public virtual DbSet<proprietaire> proprietaire { get; set; }
    }
}
