//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspprojet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messageprop
    {
        public int Id { get; set; }
        public string message_prop { get; set; }
        public Nullable<int> fk_propmsg { get; set; }
    
        public virtual proprietaire proprietaire { get; set; }
    }
}
