//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class message
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Veuillez entrer votre message", AllowEmptyStrings = false)]
        public string message_client { get; set; }
        public Nullable<int> fk_client { get; set; }

        public virtual client client { get; set; }
    }
}
